---
environment: "debug"
db:
  driver: "mysql"
  connection: "user:mypass@(127.0.0.1:3306)/mydb?parseTime=true"
  log:
    level: "info"
    output: "data/logs/crynux_bridge_db.log"
    max_file_size: 100
    max_days: 30
    max_file_num: 5
log:
  level: "debug"
  output: "data/logs/crynux_bridge.log"
  max_file_size: 100
  max_days: 30
  max_file_num: 5
http:
  host: "0.0.0.0"
  port: "5028"
data_dir:
  inference_tasks: "data/inference_tasks"
  model_images: "data/images/models"
blockchain:
  rpc_endpoint: "https://block-node.crynux.ai/rpc"
  account:
    address: ""
    private_key_file: ""
  contracts:
    netstats: "0xE9426A261D9D0F8f5179cCEFe0eb0512B1A9eb78"
    task: "0x694681C4f8C17E14920FaE7E92C8B37d606Be541"
    node: "0x309f1662e97f309b3C9d1936FEd9c1bB43eb4307"
    crynux_token: "0x95E7e7Ed5463Ff482f61585605a0ff278e0E1FFb"
  start_block_num: 1887881
  gas_limit: 42949672
relay:
  base_url: "https://relay.h.crynux.ai"
task_schema:
  stable_diffusion_inference: 'https://raw.githubusercontent.com/crynux-ai/stable-diffusion-task/main/schema/stable-diffusion-inference-task.json'
  gpt_inference: "https://raw.githubusercontent.com/crynux-ai/gpt-task/main/schema/gpt-inference-task.json"
test:
  root_address: ""
