---
environment: "debug"
db:
  driver: "mysql"
  connection: "user:mypass@(127.0.0.1:3306)/mydb?parseTime=true"
  log:
    level: "info"
    output: "data/logs/crynux_bridge_db.log"
    max_file_size: 100
    max_days: 30
    max_file_num: 5
log:
  level: "debug"
  output: "data/logs/crynux_bridge.log"
  max_file_size: 100
  max_days: 30
  max_file_num: 5
http:
  host: "0.0.0.0"
  port: "5028"
data_dir:
  inference_tasks: "data/inference_tasks"
  model_images: "data/images/models"
blockchain:
  rpc_endpoint: "https://json-rpc.crynux.evm.ra.blumbus.noisnemyd.xyz/"
  account:
    address: ""
    private_key_file: ""
  contracts:
    netstats: "0xC2c060f8C46640394E0937D75Ea977207E6df130"
    task: "0x07E149A0e372C2F54Df6358d021d700703D222D1"
    node: "0x662d296cae3f1Be2ed5803227dAd6435f1ffC438"
  start_block_num: 69603
  gas_limit: 5000000
relay:
  base_url: "https://dy.relay.crynux.ai"
task_schema:
  stable_diffusion_inference: 'https://raw.githubusercontent.com/crynux-ai/stable-diffusion-task/main/schema/stable-diffusion-inference-task.json'
  gpt_inference: "https://raw.githubusercontent.com/crynux-ai/gpt-task/main/schema/gpt-inference-task.json"
test:
  root_address: ""
