---
environment: "release"
db:
  driver: "mysql"
  connection: "crynux_bridge:crynuxbridgepass@(mysql:3306)/crynux_bridge?parseTime=true"
  log:
    level: "info"
    output: "/app/data/logs/crynux_bridge_db.log"
    max_file_size: 100
    max_days: 30
    max_file_num: 5
log:
  level: "info"
  output: "/app/data/logs/crynux_bridge.log"
  max_file_size: 100
  max_days: 30
  max_file_num: 5
http:
  host: "0.0.0.0"
  port: "5028"
data_dir:
  inference_tasks: "/app/data/inference_tasks"
  model_images: "/app/data/images/models"
blockchain:
  rps: 1 
  start_block_num: 1
  gas_limit: 8000000
  gas_price: 10
  rpc_endpoint: "https://json-rpc.testnet.crynux.ai"
  account:
    address: "0x1cCcAcb47Ed79E7Dd6584693272692585B9B41ef"
    private_key_file: "privkey.txt"
  contracts:
    netstats: "0xCF83DFC25E93687670AB87d31A24B6A892B9C08c"
    task: "0xd3e246555302CDcCd06D420681aAB4aBA715c05A"
    node: "0xFc317b2e4649D5208c5CE6f2968338ef66841642"
    qos: "0xC3E755AB19183faFD1C55478bCa23d565Ec83eeB"
relay:
  base_url: "https://dy.relay.crynux.ai"
task:
  sd_task_fee: 1000000000
  sd_xl_task_fee: 2000000000
  llm_quant_task_fee: 4000000000
  llm_task_fee: 5000000000
  repeat_num: 1 
  pending_auto_tasks_limit: 10
  auto_tasks_batch_size: 0
  timeout: 6
openrouter:
  models_file: "models.json"
task_schema:
  stable_diffusion_inference: 'https://raw.githubusercontent.com/crynux-ai/stable-diffusion-task/main/schema/stable-diffusion-inference-task.json'
  gpt_inference: "https://raw.githubusercontent.com/crynux-ai/gpt-task/main/schema/gpt-inference-task.json"
  stable_diffusion_finetune_lora: "https://raw.githubusercontent.com/crynux-ai/stable-diffusion-task/main/schema/stable-diffusion-finetune-lora-task.json"
